[package]
name = "callisto-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }

callisto-interpreter = { path = "../callisto-interpreter" }
anyhow = "1.0.97"
